notifications:
  - groupme:
      bot_id: ""
  - email:
      to: ""
      from: ""
      smtp_host: ""
      smtp_port:
      smtp_username: ""
      smtp_password: ""
      smtp_tls: true
      subject: "hello from {{program.notifications}}"
